name: pygl
channels:
  - defaults
dependencies:
  - python=3.10.4
  - jupyterlab=3.4.4
  - pip
  - pip:
    - glfw==2.5.4
    - imgui==1.4.1
    - imageio==2.20.0
    - ipywidgets==8.0.1
    - matplotlib==3.5.2
    - pyopengl==3.1.6
    - trimesh==3.12.9